<?php
defined('ABSPATH') || exit;
/** @var bool $quizably_built Whether assets/dist/admin.js exists. Set by Menu::render_app(). */
$quizably_built = $quizably_built ?? true;
?>
<div id="quizably-admin-app" class="quizably-admin-app">
    <?php if ($quizably_built) : ?>
    <div class="quizably-admin-app__loading">
        <?php esc_html_e('Loading…', 'quizably'); ?>
    </div>
    <?php else : ?>
    <?php
    // Self-contained on purpose: this fires precisely when the plugin's own
    // built CSS/JS (assets/dist/) is missing, so it cannot lean on either of
    // them. Admin notices are suppressed on this screen (Menu::suppress_notices),
    // so this placeholder is the only way to surface the problem instead of an
    // unexplained, permanent spinner. Its CSS is enqueued the normal way via
    // Admin\Assets::enqueue_build_notice_styles() — not inlined here — since
    // it fires on `admin_enqueue_scripts`, well before this template renders.
    ?>
    <div class="quizably-build-notice">
        <h2><?php esc_html_e('Quiz Builder assets are not built yet', 'quizably'); ?></h2>
        <p>
            <?php esc_html_e(
                'This looks like a source checkout without a production build — assets/dist/ is generated by the build step and is not committed to git. Run this in the plugin directory, then reload this page:',
                'quizably'
            ); ?>
        </p>
        <pre>npm install
npm run build</pre>
        <p class="quizably-build-notice__hint">
            <?php esc_html_e('See README.md for full setup instructions.', 'quizably'); ?>
        </p>
    </div>
    <?php endif; ?>
</div>
